### ISSUE TITLE
Display bug on windows

### ISSUE THREAD

**Issue by Xymanek** [symfony/thanks#16]
![zc9hptrcshaza-bp0djdkg](https://user-images.githubusercontent.com/2865341/34256742-7943785a-e65f-11e7-9c27-f114240ed762.png)

I tested cmd, cmd inside phpstorm and powershell - same thing on the left everywhere

Installed globally (`composer global require symfony/thanks`)

**Comment by stof** [comment]
hmm, we need a fallback avoiding using Unicode stars on Windows, as the windows terminal odes not use UTF-8.

**Comment by nicolas-grekas** [comment]
PR welcomed :)
