### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by a-komarev** [symfony/thanks#24]
Thank you for such good thing, sometimes it really missing feature to tell somebody thank you :heart:

**Comment by cpxPratik** [comment]
It would have been even better, if this plugin's feature came integrated with composer. So we only need to run command `composer thanks` if we want to.

**Comment by nicolas-grekas** [comment]
@cpxPratik "just" needs someone to actually do it :)

**Comment by nicolas-grekas** [comment]
Thanks for the love :)
