### ISSUE TITLE
Do not display message after thanks have been given

### ISSUE THREAD

**Issue by falnyr** [symfony/thanks#29]
After successful run of `composer thanks` shouldn't the message stop displaying?

**Comment by nicolas-grekas** [comment]
The message could be hidden when all deps are already starred. But knowing
so requires an extra HTTP query. It's a trade-off between network latency
and a few extra displays.
I choose to favor performance.
If you know/want to improve that aspect, PR welcome.

**Comment by fabpot** [comment]
Is it fixed by #38?

**Comment by nicolas-grekas** [comment]
Not precisely, but not that the reminder is displayed less often, it might be less an issue.
Closing for now. Please come back with an implementation if you want, anyone :)
