### ISSUE TITLE
This evil thing could at least ask whether I want to star a bazillion of dependencies

### ISSUE THREAD

**Issue by simPod** [symfony/thanks#30]
So I was like "Cool, let's see what this thing does." and did the biggest mistake in my live by typing `composer thanks` and pressing enter in my command line

```
Stars sent to:
[following output was censored as it contains all github repositories in the world]
```

It could at least politely ask whether I want to send stars to 558323193262310564 repositories...

**Comment by nicolas-grekas** [comment]
Closing as clearly the tone here is not favoring any constructive discussion.
See #24
