### ISSUE TITLE
PHP 7.0 version

### ISSUE THREAD

**Issue by mocheaz** [symfony/thanks#32]
Just installed Laravel that install symphony that install this package

I got this
```
symfony/thanks v1.0.1 requires php ^5.5.9|^7.0.8 -> your PHP version (7.0.4) does not satisfy that requirement.
```
Why force people to have 7.0.8.

**Comment by nicolas-grekas** [comment]
The reason is that we took the same minimum PHP version as Symfony, which requires ^7.0.8 because previous versions have a serious bug around the serializer, so you'd better upgrade.
But since this specific package doesn't use serialize(), feel free to send a PR and change that to `^7.0.0`.

**Comment by mocheaz** [comment]
Thanks.

Moche Azoulay
0527629782
