### ISSUE TITLE
symfony/thanks v1.0.2 requires composer-plugin-api ^1.1 -> no matching package found.

### ISSUE THREAD

**Issue by kalsolio** [symfony/thanks#36]
- Installation request for symfony/thanks v1.0.2 -> satisfiable by symfony/thanks[v1.0.2].
    - symfony/thanks v1.0.2 requires composer-plugin-api ^1.1 -> no matching package found.

**Comment by nicolas-grekas** [comment]
Thanks for the report.
This will be fixed by #37
You can also and preferably upgrade to a newer version of Composer. v1.0.2 is quite old now.
