### ISSUE TITLE
Auto starring against github TOS?

### ISSUE THREAD

**Issue by giorgio79** [symfony/thanks#49]
Automated bulk activity is disallowed according to github tos...

Auto starring could fit this description https://help.github.com/articles/github-terms-of-service/#c-acceptable-use

**Comment by nicolas-grekas** [comment]
Hello,
this doesn't do anything automatically: the command has to be run from the command line by actual people.
Nothing happens otherwise.
Then, this just uses the regular GitHub API, which allows this setting stars on repos.
