### ISSUE TITLE
An option to give thanks only obviously specified dependencies

### ISSUE THREAD

**Issue by bocharsky-bw** [symfony/thanks#50]
What about to add an option to give thanks only obviously-specified dependencies, i.e. those dependencies you have in `require`/`require-dev` sections of `composer.json`.

Actually, I'd say it should be a default behavior. But now, if I execute `composer thanks` this plugin gives thanks to all the packages, even those I've never used directly.

**Comment by nicolas-grekas** [comment]
Hello,
feel free to add an option to the command.
It should not be the default IMHO because we are all actually relying on the deps of our deps as heavily as our direct deps. Nothing would work without the hard work of core package maintainers.
