### ISSUE TITLE
Failed on doctrine-extensions

### ISSUE THREAD

**Issue by FanchTheSystem** [symfony/thanks#51]
Hello,

composer thanks failed with this error:
                                                                          
```
  [Composer\Downloader\TransportException]                                
  Could not resolve to a Repository with the name 'doctrine-extensions'.  
```
                                                                          
Here is my composer.json : https://github.com/sil-project/Platform/blob/master/composer.json

**Comment by nicolas-grekas** [comment]
Looks like https://github.com/orocrm/doctrine-extensions has been renamed to https://github.com/oroinc/doctrine-extensions

**Comment by FanchTheSystem** [comment]
It work, thank you !
