### ISSUE TITLE
Star only root dependencies

### ISSUE THREAD

**Issue by Pierstoval** [symfony/thanks#64]
There is a lot of people arguing against Symfony/Thanks because they don't think it's useful/relevant/whatever.

Mitchell on the public slack pointed something interesting ([link](https://symfony-devs.slack.com/archives/C9F9AMSNP/p1538121050000100)):

> Mitchell:
> If `symfony/thanks` would only star the top level dependencies them I wouldn't mind (as much). Starring every depedency that a package has seems a bit overkill, especially if that depedency should have been a suggest and not an actual require (and I'm sure there a lot of those).

IMO this is a great idea: we actually better like the dependencies we **really** add to the project, but sometimes we just don't care about our deps' deps, because well it ends up starring tons of projects on Github we wouldn't even be interested about, just because our dependencies depend on them.

Imagine doing a "thanks" plugin for NodeJS: one run would star hundreds of projects that are not really useful but just depended on because of legacy/bad practices/whatever issue that is not yet fixed via `npm audit fix`... For PHP it could be the same for some old versions of some packages, that's why root deps only is maybe a better option.

And it better reflects the _real_ popularity of a package.

Proposal: 

* Either star root dependencies only by default and add `--with-dependencies` option to star other packages.
* Or just keep the current behavior and add `--root-only|--root` option.

WDYT?

**Comment by javiereguiluz** [comment]
Just a minor comment. This is not true --> *"There is a lot of people arguing against ..."*  It's not "a lot of people", it's just a few people (vs the 5,000 people that have run symfony/thanks so far).

**Comment by nicolas-grekas** [comment]
Hi, thanks for proposing, but this package is as it has been designed. First level or 2nd level is a virtual criteria: all deps are required to make a package work, there are no boundaries to "thanking" with symfony/thanks.
