### ISSUE TITLE
Feature Idea: Also watch for new releases

### ISSUE THREAD

**Issue by mablae** [symfony/thanks#65]
Github recently introduced the new "Releases only" watch option for repositories. 

![grafik](https://user-images.githubusercontent.com/389360/49311684-1d876980-f4e2-11e8-9619-ef0343dcdaae.png)

https://github.com/isaacs/github/issues/410#issuecomment-442385230

The idea is: 
Introduce a new flag or command to not just "star" the repo but also mark it as "watch for new releases". 

Let me know what you think about it.

**Comment by nicolas-grekas** [comment]
Interesting :) Let's give it a try!

**Comment by akshayachar2011** [comment]
Hi @nicolas-grekas , Would like to give a try for this feature.

**Comment by nicolas-grekas** [comment]
What would be the UX? Only root deps? Separate command?

**Comment by Calinou** [comment]
Wouldn't release tracking be better covered by a tool like [dependabot](https://dependabot.com/)?
