### ISSUE TITLE
Token is not stored

### ISSUE THREAD

**Issue by stancl** [symfony/thanks#71]
Running `composer thanks` and supplying it with a valid token does star the repos, but it does not store the token. `~/.composer/auth.json` does not exist on my computer.

Creating `~/.composer/auth.json` with `{}` as the content, `chown`ing and running `composer thanks` again fixes this.

Since `~/.composer` is writable only by root, I think a note about having to create & `chown` the file  should be added to README.

**Comment by nicolas-grekas** [comment]
That very specific to your setup: ~/.composer is writable only by root should be writable by the current user, not only by root. That's an issue on your side to me.
