### ISSUE TITLE
Improve code documentation

### ISSUE THREAD

**Issue by JohJohan** [symfony/thanks#72]
Q | A
-- | --
Branch? | master
Bug fix? | no
New feature? | no
BC breaks? | no
Deprecations? | no
Tests pass? | 
License | MIT
Doc PR

We could improve code documentation like:

In `https://github.com/symfony/thanks/blob/master/src/GitHubClient.php`

Declare what variables are
```
/**
* Composer
*/
private $composer;
```

Document what kind of value we expect:
```
/**
* @param array $failures
*/
 public function getRepositories(array &$failures = null)
```

Etc let me know what you think? We could also add some code doocumentation in docs. declare what variable is used for etc

**Comment by nicolas-grekas** [comment]
We don't add docblocks when they don't provide clear added value.
Thanks for the suggestion anyway!
