### ISSUE TITLE
composer thanks works but getting "[Composer\Downloader\TransportException]"

### ISSUE THREAD

**Issue by chloebrqt** [symfony/thanks#82]
Hello,

I'm proud to have finally run `composer thanks` on a small project I developed :smiley:  
But after running it, I get the following error :
```
[Composer\Downloader\TransportException]                                                      
  The "https://api.github.com/graphql" file could not be downloaded (HTTP/1.1 502 Bad Gateway)
```
I thought it hadn't worked, but after looking at the issues mentionning graphql in this repo, I realized it had actually worked & I'm now starring the ~ hundred repos I use in the project. Still, I was wondering why there was this mistake and if it was normal, thought I'd tell you about it.

Have a nice day :)

**Comment by nicolas-grekas** [comment]
Hi, thanks for the report, and thanks for running the command :)
A 502 looks like an issue on GitHub's side,not sure we can do more...

**Comment by chloebrqt** [comment]
My pleasure :)
Ok, no problem! I also received an email from Github saying authenticating via URL query parameters (with the personal access token, as composer thanks asked me to do) is deprecated, maybe it has something to do with that.

**Comment by nicolas-grekas** [comment]
For the notice about the access token, upgrade to composer 1.9.3+ and that should fix it!

**Comment by chloebrqt** [comment]
Ohh ok, thanks for the info!
I close the issue then :)

**Comment by PhillipRichdale** [comment]
I get this error (Symfony 5.x) when trying to run `composer global require symfony/thanks && composer thanks`:
`In RemoteFilesystem.php line 441:
The "https://api.github.com/graphql" file could not be downloaded (HTTP/1.1 502 Bad Gateway)`

**Comment by nulf** [comment]
@PhillipRichdale : I got the exact same error even though I created a freshly baked github oauth-token and everything. I just ran the exact command again and the second time I did not recieve the error.
