### ISSUE TITLE
syntax error, unexpected '}'

### ISSUE THREAD

**Issue by tanthammar** [symfony/thanks#86]
```
Parse error: syntax error, unexpected '}' in symfony/thanks/src/GitHubClient.php on line 108
```

You are missing a ; on line 107.
```
$this->rfs = new HttpDownloader($io, $composer->getConfig())
```

**Comment by fer-plus** [comment]
> Parse error: syntax error, unexpected '}' in /Users/tina/Sites/bookons-api/vendor/symfony/thanks/src/GitHubClient.php on line 108
> 
> You are missing a ; on line 107.

Same here. Just wanted to report too.

**Comment by nicolas-grekas** [comment]
Oops thank, v1.2.7 pushed.
