### ISSUE TITLE
CLI behave like a malware

### ISSUE THREAD

**Issue by VarunAgw** [symfony/thanks#94]
I saw a prompt about it when working with composer.

Out of curiosity, I installed and ran it.

It didn't mention anywhere what it does exactly (thanking other developers is a bit vague). I only found out what it does at the very last time after I ran the code and it starred all the repositories without my permission.

There was no explanation, no permission request, no warning and no undo button. It access my github without my permission (just like a malware would do).

**Comment by nicolas-grekas** [comment]
I checked the code, it's pretty clear about the fact this sends github stars, eg "Give thanks (in the form of a GitHub ⭐)"
